signin:
  url: /login
  param: { module: user, action: signin }

signout:
  url: /logout
  param: { module: user, action: signout }

register:
  url: /register
  param: { module: user, action: register }

request_password:
  url: /request_password
  param: { module: user, action: requestPassword }

reset_password:
  url: /reset_password/:user/:code
  param: { module: user, action: resetPassword }

activation:
  url: /activate/:code
  param: { module: user, action: activate }